let products=[],cart=JSON.parse(localStorage.getItem('maheer_cart')||'[]');
const $=id=>document.getElementById(id),money=n=>'৳'+Number(n||0).toLocaleString('en-US');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const session='web-'+(crypto.randomUUID?crypto.randomUUID():Date.now());
function saveCart(){localStorage.setItem('maheer_cart',JSON.stringify(cart));$('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)}
async function loadSettings(){try{const s=await fetch('/api/settings').then(r=>r.json());$('aboutText').textContent=s.about_store||'';$('footerAbout').textContent=s.store_info||s.about_store||'';const links=[['wa','whatsapp_link'],['ig','instagram_link'],['tt','tiktok_link'],['fb','facebook_link']];links.forEach(([id,k])=>{if(s[k])$(id).href=s[k];else $(id).style.opacity='.45'});links.forEach(([id,k])=>{const f={wa:'fwa',ig:'fig',tt:'ftt',fb:'ffb'}[id];if(s[k])$(f).href=s[k];});}catch{}}
async function loadProducts(q=''){try{products=await fetch('/api/products'+(q?'?search='+encodeURIComponent(q):'')).then(r=>r.json());renderProducts(products);renderChips(products)}catch{}}
function renderChips(ps){const cats=[...new Set(ps.map(p=>p.category))];$('chips').innerHTML='<button class="chip active" onclick="loadProducts()">সব</button>'+cats.map(c=>`<button class="chip" onclick="filterCat('${esc(c)}')">${esc(c)}</button>`).join('')}
function filterCat(cat){const x=products.filter(p=>p.category===cat);renderProducts(x);document.querySelectorAll('.chip').forEach(b=>b.classList.toggle('active',b.textContent===cat))}
function renderProducts(ps){$('productGrid').innerHTML=ps.map(p=>{const discount=p.old_price>p.price?Math.round((1-p.price/p.old_price)*100):0;return `<article class="product"><button class="heart" onclick="addToCart(${p.id})">♡</button>${discount?`<span class="badge">-${discount}%</span>`:''}<div class="pic"><img src="${p.image||'assets/hero-model.png'}" alt="${esc(p.name)}"></div><div class="product-body"><div class="product-cat">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="price"><b>${money(p.price)}</b>${p.old_price?`<del>${money(p.old_price)}</del>`:''}</div><button class="buy" onclick="addToCart(${p.id})">🛒 কার্টে যোগ করুন</button></div></article>`}).join('')||'<div class="empty">কোনো পণ্য পাওয়া যায়নি।</div>'}
function addToCart(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id:Number(p.id),qty:1});saveCart();openCart()}
function openCart(){renderCart();openModal('cartModal')}
function renderCart(){const rows=cart.map(x=>{const p=products.find(p=>Number(p.id)===x.id);if(!p)return '';return `<div class="cart-row"><img src="${p.image||'assets/hero-model.png'}"><div><b>${esc(p.name)}</b><small style="display:block;color:#888">${money(p.price)} × ${x.qty}</small><button onclick="changeQty(${x.id},-1)">−</button> <button onclick="changeQty(${x.id},1)">+</button></div><b>${money(p.price*x.qty)}</b></div>`}).join('');$('cartItems').innerHTML=rows||'<p>কার্টে কোনো পণ্য নেই।</p>';const total=cart.reduce((s,x)=>{const p=products.find(p=>Number(p.id)===x.id);return s+(p?p.price*x.qty:0)},0);$('cartTotal').textContent=money(total)}
function changeQty(id,d){const x=cart.find(x=>x.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart();renderCart()}
function checkout(){if(!cart.length){alert('কার্টে পণ্য যোগ করুন।');return}closeModal('cartModal');openModal('orderModal')}
$('orderForm').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));b.items=cart;const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});const j=await r.json();$('orderMsg').innerHTML=r.ok?`<div style="padding:14px;background:#f3f0e8;border-radius:8px;margin-top:10px">অর্ডার সফল হয়েছে। আপনার অর্ডার নম্বর: <b>${j.order_id}</b><br>মোট: <b>${money(j.total)}</b></div>`:`<div style="color:#a00;margin-top:8px">${esc(j.error||'অর্ডার করা যায়নি।')}</div>`;if(r.ok){cart=[];saveCart();e.target.reset()}};
async function trackOrder(){const code=$('trackInput').value.trim();if(!code)return;$('trackResult').textContent='খোঁজা হচ্ছে...';const r=await fetch('/api/orders/'+encodeURIComponent(code));const j=await r.json();$('trackResult').textContent=r.ok?`অর্ডার: ${j.order_code} • অবস্থা: ${j.status} • মোট: ${money(j.total)}`:(j.error||'পাওয়া যায়নি।')}
async function openAgents(){openModal('agentModal');try{const a=await fetch('/api/agents').then(r=>r.json());$('agentList').innerHTML=a.length?a.map(x=>`<div class="agent-card"><b>${esc(x.name)}</b><small style="display:block;color:#888">${esc(x.phone)}</small>${x.whatsapp?`<a href="https://wa.me/${String(x.whatsapp).replace(/\D/g,'')}" target="_blank">◉ WhatsApp</a>`:''}${x.messenger?`<a href="${esc(x.messenger)}" target="_blank">Messenger</a>`:''}</div>`).join(''):'<p>এখন কোনো সক্রিয় Agent নেই।</p>'}catch{$('agentList').innerHTML='<p>Agent তথ্য পাওয়া যাচ্ছে না।</p>'}}
function openChat(){openModal('chatModal')}
$('chatForm').onsubmit=async e=>{e.preventDefault();const input=$('chatInput'),msg=input.value.trim();if(!msg)return;addBubble(msg,'me');input.value='';const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:msg,session})});const j=await r.json();addBubble(j.reply||'এখন উত্তর দেওয়া সম্ভব নয়।','bot')};
function addBubble(t,c){const d=document.createElement('div');d.className='bubble '+c;d.textContent=t;$('chatLog').appendChild(d);$('chatLog').scrollTop=$('chatLog').scrollHeight}
function openModal(id){$(id).classList.add('show')}function closeModal(id){$(id).classList.remove('show')}function scrollToId(id){$(id)?.scrollIntoView({behavior:'smooth'})}
$('hamb').onclick=()=>{$('nav').style.display=$('nav').style.display==='flex'?'none':'flex'};$('searchOpen').onclick=()=>{$('searchbar')?.classList.toggle('show');$('search').focus()};$('searchBtn').onclick=()=>loadProducts($('search').value.trim());$('search').onkeydown=e=>{if(e.key==='Enter')loadProducts(e.target.value.trim())};
$('year').textContent=new Date().getFullYear();saveCart();loadSettings();loadProducts();
